force_arm:
  target:
    entity:
      integration: securitas
      domain: alarm_control_panel

force_arm_cancel:
  target:
    entity:
      integration: securitas
      domain: alarm_control_panel
